package com.mycompany.myapp;


import com.codename1.components.WebBrowser;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Button;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.BrowserComponent;
import com.codename1.ui.Command;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BorderLayout;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        new Form1().show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }
    
    class Form1 extends Form {

        public Form1() {
            
            super();

            setTitle("Form 1");
            
            Button btn = new Button("Call Browser");
            btn.addActionListener((ActionListener) (ActionEvent evt) -> {
                
                final Form2 f2 = new Form2();
                Command backCommand = new Command("Back") {
                    @Override
                    public void actionPerformed(ActionEvent ev) {
                        Form1.this.showBack();
                    } 
                }; 
                f2.setBackCommand(backCommand);
                f2.show();        
                
            });
            
            setLayout(new BorderLayout());
            addComponent(BorderLayout.CENTER, btn);
            
        }
        
        
    }
    
    class Form2 extends Form {
        public Form2() {  
            super();
            setTitle("Form 2 - WebBrowser");
            WebBrowser browser =  new WebBrowser("http://codenameone.com");
            setLayout(new BorderLayout());
            addComponent(BorderLayout.CENTER, browser);
        }
    }

}
